# Generated by Django 5.1 on 2024-09-15 23:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='users/UserDefaultBg.jpg', upload_to=accounts.models.user_directory_path_banner),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
